theme = "apollo"
taxonomies = [{ name = "tags" }]
base_url = "https://enismustafaj.github.io"
compile_sass = false

[markdown]
github_alerts = false
insert_anchor_links = "right"

[markdown.highlighting]
error_on_missing_language = false
style = "inline"
theme = "github-dark"

[extra]
theme = "auto"
socials = [
  { name = "github", url = "https://github.com/enismustafaj/", icon = "github" }
]
menu = [
    { name = "home", url = "/", weight = 1 },
    { name = "about", url = "/about", weight = 2 },
    { name = "posts", url = "/posts", weight = 3 },
]
